name: liste_de_courses
description: Liste de courses partagée (Android, iPhone, Windows)
publish_to: 'none'
version: 0.6.0+6

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.4
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icone_ronde.png
    - assets/donnees_maquette.json
    - assets/catalogue/
  fonts:
    - family: Atkinson
      fonts:
        - asset: assets/polices/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/polices/AtkinsonHyperlegible-Bold.ttf
          weight: 700
        - asset: assets/polices/AtkinsonHyperlegible-Italic.ttf
          style: italic
